FROM gurobi/optimizer:latest

# Install InRetEnsys with all dependencies, wheels are nice!
WORKDIR /app

COPY dist/InRetEnsys-0.2a7-py3-none-any.whl .
RUN pip install InRetEnsys-0.2a7-py3-none-any.whl

COPY main.py .
