# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Coverage Report

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate Coverage Report
      run: |
        bash tests.sh
        coverage xml
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        #project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        # or
        api-token: ${{ secrets.CODACY_ACCOUNT_TOKEN }}
        # coverage-reports: reports
        # or a comma-separated list for multiple reports
        # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
